services:
  clustta-docs:
    image: clustta-docs:latest
    container_name: clustta-docs
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.clustta-docs.rule=Host(`docs.clustta.com`)"
      - "traefik.http.services.clustta-docs.loadbalancer.server.port=80"
      - "traefik.http.routers.clustta-docs.entrypoints=websecure"
      - "traefik.http.routers.clustta-docs.tls.certresolver=myresolver"
    networks:
      - web
    restart: always
    environment:
      DOCS_BASE_URL: https://docs.clustta.com
      CLUSTTA_API_TARGET: https://api.clustta.com

networks:
  web:
    external: true
    name: clustta-web